# SPDX-FileCopyrightText: 2024 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
    uses: ./.github/workflows/build.yml
    with:
      disable-cache: true

  crates-io:
    name: crates.io
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # ratchet:dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # ratchet:Swatinem/rust-cache@v2

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  github:
    name: GitHub Releases
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # ratchet:actions/download-artifact@v5
        with:
          path: /tmp/artifacts

      - name: Prepare assets
        env:
          ARTIFACTS: ${{ steps.download.outputs.download-path }}
        id: prepare
        run: |
          asset_path="/tmp/assets"
          mkdir -p "$asset_path"
          for artifact in "$ARTIFACTS"/*/; do
            basename "$artifact" | \
              xargs -I {} zip -jr "$asset_path"/{}.zip "$artifact"
          done

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create --draft --verify-tag "$TAG" /tmp/assets/*.zip
